package com.whatsappbot.video.dialogue;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * A structured dialogue between Bhaiya (explainer) and Chitti (learner).
 * Generated by the LLM via DialogueScriptService; submitted to the renderer worker.
 */
public record DialogueScript(
        @JsonProperty("topic") String topic,
        @JsonProperty("turns") List<DialogueTurn> turns
) {}
