package com.whatsappbot.lead;

public enum LeadIntentCategory {
    PRICE_INQUIRY, SERVICE_REQUEST, BOOKING_REQUEST, DEMO_REQUEST,
    COMPLAINT, SUPPORT_REQUEST, COMPETITOR_INTEREST, GENERAL_QUESTION
}
