-- Video scripts generated by AI for content ideas
CREATE TABLE IF NOT EXISTS video_scripts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenants(id),
    content_idea_id UUID REFERENCES content_ideas(id),
    title           VARCHAR(300) NOT NULL,
    platform_code   VARCHAR(50)  NOT NULL DEFAULT 'INSTAGRAM',
    content_type    VARCHAR(50)  NOT NULL DEFAULT 'REEL',
    style           VARCHAR(100) NOT NULL DEFAULT 'ENGAGING',
    duration_secs   INT          NOT NULL DEFAULT 30,
    hook            TEXT,
    script_body     TEXT,
    shot_list       JSONB        NOT NULL DEFAULT '[]',
    hashtags        JSONB        NOT NULL DEFAULT '[]',
    caption         TEXT,
    music_suggestion VARCHAR(200),
    status          VARCHAR(50)  NOT NULL DEFAULT 'DRAFT',
    generated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_video_scripts_tenant ON video_scripts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_video_scripts_status  ON video_scripts(tenant_id, status);
